Anpr
2022PO3/Raspberry_pi pull request #1
Opened 2022-10-28 13:10 UTC by Rune2003

2022-10-28 19:41 UTC, Robin-Martens requested changes
I think this already looks very fantastic! The comments I made are primilarily nits about types and some shorthand syntaxes. Overall, you did a very great job!

In the future, we do want to add a function which can send the licence plate to the Backend API, but this has to be developed first in the Backend.

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/pyproject.toml
> +build-backend = 'setuptools.build_meta'
Files always end with a new line due to convention, try adding one here.

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/setup.cfg
> +    anpr.parkeergarage-c76e9940c139.json
Nit: newline

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/setup.py
> +    setup()
Nit: newline

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +    def match_format(self, formats: list):
You can define the output type of the function like so: `def match_format(self, formats: list) -> list[LicensePlateResult`.

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +            matches += re.findall(f, self.text)
```suggestion
        matches = [re.findall(f, self.text) for f in formats]
```

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +    def debug_print(self, text, verbosity):
Nit: maybe mark the output type of the function: `def debug_print(self, text:  str, verbosity: int) -> None`.

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +        squareKern = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
I think that you copied this from somewhere, because otherwise, brilliant! This is well beyond my cap.

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +    def pick_license_plate_location(self, gray, candidates):
Nit: add types to function heading (I think `gray` is a `numpy`-array).

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
What's the added benefit for converting the image to grayscale?

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +def cleanup_text(text):
```suggestion
def cleanup_text(text: str) -> str:
```

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +def detectLicensePlate(imagePath, anpr):
Nit: maybe be consistent with the case type (PEP 8 pescribes snake_case).

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +def takePhoto(path: str):
Idem dito here.

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/motion_detection.py
> +detect(directory + '/input.mov', directory + '/bg.mov')
Nit: add newline.

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +                    formatted_results += new_results
```suggestion
formatted_results = lp_results.map(lambda result: result.match_format(self.formats)
```

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +                    formatted_results += new_results
You can choose to use a list comprehension or map (the latter is most often faster).

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +    def find_and_ocr(self, image, doSelection=True):
Nit: add types to function heading.

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +    def locate_license_plate_candidates(self, gray, keep=15):
Nit: add types to function heading.

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +    def debug_imshow(self, title, image, verbosity: int, waitKey=False):
Nit: add types to function heading.

2022-10-28 19:41 UTC, Robin-Martens commented on ANPR/src/anpr/license_plate_recognition.py
> +            formats = [f.replace('L', '[A-Z]') for f in formats]
Nit: you can do this in one line:
```python
formats = [f.replace("N", "[0-9]").replace("L", "[A-Z}") for f in formats]
```

2022-11-15 15:38 UTC, TuurVernieuwe approved these changes

2022-11-22 07:26 UTC, Robin-Martens commented
This will be implemented in the Backend instead.

2022-11-22 07:26 UTC, closed without merging